name: CI/CD - Build & Push (Examen)

on:
  push:
    branches:
      - main
      - master
      - desarrollo

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: ⬇Establecer Nombre de Repositorio en Minúsculas
      id: set_repo_name
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Construir y Publicar Imagen Docker
      uses: docker/build-push-action@v6
      with:
        push: true
        # CORRECCIÓN: Cambiamos ':' por '-' para que la etiqueta sea válida.
        # Resultado: ghcr.io/usuario/repo:pablo-calc-1.0.1
        tags: ghcr.io/${{ env.REPO_NAME }}:pablo-calc-1.0.1 
        context: .